import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import test from "node:test";

const revision = "b66988b856946ff028085323ff502796b97e0012";
const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url));
const text = (path) => read(path).toString("utf8");
const manifest = JSON.parse(text("vendor/hhm-interfaces/platform/SOURCE.json"));
const generatedSql = read("vendor/hhm-interfaces/platform/sql/schema.sql");
const migrationSql = read("migrations/202609080001_hhm_platform_generated.sql");
const hardening = text("migrations/202609080002_hhm_platform_hardening.sql");

test("vendored platform artifacts have immutable provenance and digests", () => {
  assert.equal(manifest.repository, "https://github.com/hacker-house-medellin/hhm-interfaces");
  assert.equal(manifest.revision, revision);
  assert.equal(manifest.release_state, "production");
  assert.equal(manifest.artifacts.length, 4);

  for (const artifact of manifest.artifacts) {
    const contents = read(artifact.vendored_path);
    assert.equal(contents.byteLength, artifact.bytes, artifact.vendored_path);
    assert.equal(
      createHash("sha256").update(contents).digest("hex"),
      artifact.sha256,
      artifact.vendored_path,
    );
    assert.match(contents.toString("utf8", 0, 160), /GENERATED by ores-contracts/);
  }
  assert.deepEqual(migrationSql, generatedSql);
});

test("generated platform reservation cannot collide with legacy reservation storage", () => {
  const generated = generatedSql.toString("utf8");
  assert.match(generated, /CREATE TABLE hhm_space_reservations \(/);
  assert.doesNotMatch(generated, /(?:CREATE|ALTER|DROP|TRUNCATE) TABLE (?:public\.)?hhm_reservations\b/i);
  assert.doesNotMatch(hardening, /(?:CREATE|ALTER|DROP|TRUNCATE) TABLE (?:public\.)?hhm_reservations\b/i);
});

test("hardening migration is additive and names every platform safety boundary", () => {
  assert.doesNotMatch(hardening, /\b(?:DROP|TRUNCATE)\b|\bDELETE\s+FROM\b/i);
  assert.match(hardening, /hhm_space_reservations_no_active_overlap/);
  assert.match(hardening, /ENABLE ROW LEVEL SECURITY/);
  assert.match(hardening, /FORCE ROW LEVEL SECURITY/);
  assert.match(hardening, /CREATE FUNCTION public\.hhm_transition_reservation/);
  assert.match(hardening, /CREATE FUNCTION public\.hhm_transition_guest_pass/);
  assert.match(hardening, /CREATE FUNCTION public\.hhm_transition_access_grant/);
  assert.match(hardening, /CREATE FUNCTION public\.hhm_transition_visit/);
  assert.match(hardening, /CREATE FUNCTION public\.hhm_record_access_decision/);
  assert.match(hardening, /platform ledger rows are append-only/);
  assert.match(hardening, /NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS/);
  assert.doesNotMatch(hardening, /SET search_path = pg_catalog, public/);
});

test("all generated tenant tables participate in the RLS allowlist", () => {
  const generatedTables = [...generatedSql.toString("utf8").matchAll(/CREATE TABLE (hhm_[a-z_]+) \(/g)]
    .map((match) => match[1])
    .sort();
  const rlsBlock = hardening.match(/FOREACH table_name IN ARRAY ARRAY\[([\s\S]*?)\]\s+LOOP/);
  assert.ok(rlsBlock, "RLS table allowlist must be explicit");
  const rlsTables = [...rlsBlock[1].matchAll(/'(hhm_[a-z_]+)'/g)]
    .map((match) => match[1])
    .sort();
  assert.deepEqual(rlsTables, generatedTables);
});

test("Cargo consumes the same full interface revision", () => {
  assert.match(text("crates/persistence/Cargo.toml"), new RegExp(`rev = "${revision}"`));
  assert.match(text("Cargo.lock"), new RegExp(`rev=${revision}#${revision}`));
});
