-- Generated by declarative-postgres-migrate (dpm)
-- desired (source): schema file /Users/maca5/codes/hacker-house-medellin/hhm-lib-core/schema/schema.sql
-- current (target): postgresql://postgres:***@127.0.0.1:55610/hhm_target
-- Converges the target onto the source. Review before applying.
-- dpm never applies SQL unless explicitly told to (dpm apply --yes).

BEGIN;

-- add column: public.hhm_applications.allergy_notes
ALTER TABLE "public"."hhm_applications" ADD COLUMN IF NOT EXISTS "allergy_notes" character varying(2000);

-- add column: public.hhm_applications.noise_sensitivity
ALTER TABLE "public"."hhm_applications" ADD COLUMN IF NOT EXISTS "noise_sensitivity" character varying(32) NOT NULL;

-- add column: public.hhm_applications.light_sensitivity
ALTER TABLE "public"."hhm_applications" ADD COLUMN IF NOT EXISTS "light_sensitivity" character varying(32) NOT NULL;

-- add column: public.hhm_applications.room_preference_notes
ALTER TABLE "public"."hhm_applications" ADD COLUMN IF NOT EXISTS "room_preference_notes" character varying(2000);

-- add column: public.hhm_applications.roommate_preference
ALTER TABLE "public"."hhm_applications" ADD COLUMN IF NOT EXISTS "roommate_preference" character varying(32) NOT NULL;

-- add column: public.hhm_applications.preferred_room_occupancy
ALTER TABLE "public"."hhm_applications" ADD COLUMN IF NOT EXISTS "preferred_room_occupancy" smallint NOT NULL;

-- add column: public.hhm_applications.roommate_for_lower_cost
ALTER TABLE "public"."hhm_applications" ADD COLUMN IF NOT EXISTS "roommate_for_lower_cost" boolean NOT NULL;

-- add column: public.hhm_applications.roommate_for_social_connection
ALTER TABLE "public"."hhm_applications" ADD COLUMN IF NOT EXISTS "roommate_for_social_connection" boolean NOT NULL;

-- add column: public.hhm_applications.accommodation_data_consent
ALTER TABLE "public"."hhm_applications" ADD COLUMN IF NOT EXISTS "accommodation_data_consent" boolean NOT NULL;

-- add constraint: hhm_applications_accommodation_consent on public.hhm_applications
ALTER TABLE "public"."hhm_applications" ADD CONSTRAINT "hhm_applications_accommodation_consent" CHECK (accommodation_data_consent) NOT VALID;
ALTER TABLE "public"."hhm_applications" VALIDATE CONSTRAINT "hhm_applications_accommodation_consent";

-- add constraint: hhm_applications_light_sensitivity on public.hhm_applications
ALTER TABLE "public"."hhm_applications" ADD CONSTRAINT "hhm_applications_light_sensitivity" CHECK ((((light_sensitivity)::text = 'none'::text) OR ((light_sensitivity)::text = 'low'::text) OR ((light_sensitivity)::text = 'moderate'::text) OR ((light_sensitivity)::text = 'high'::text) OR ((light_sensitivity)::text = 'prefer_not_to_say'::text))) NOT VALID;
ALTER TABLE "public"."hhm_applications" VALIDATE CONSTRAINT "hhm_applications_light_sensitivity";

-- add constraint: hhm_applications_noise_sensitivity on public.hhm_applications
ALTER TABLE "public"."hhm_applications" ADD CONSTRAINT "hhm_applications_noise_sensitivity" CHECK ((((noise_sensitivity)::text = 'none'::text) OR ((noise_sensitivity)::text = 'low'::text) OR ((noise_sensitivity)::text = 'moderate'::text) OR ((noise_sensitivity)::text = 'high'::text) OR ((noise_sensitivity)::text = 'prefer_not_to_say'::text))) NOT VALID;
ALTER TABLE "public"."hhm_applications" VALIDATE CONSTRAINT "hhm_applications_noise_sensitivity";

-- add constraint: hhm_applications_room_occupancy on public.hhm_applications
ALTER TABLE "public"."hhm_applications" ADD CONSTRAINT "hhm_applications_room_occupancy" CHECK (((preferred_room_occupancy >= 1) AND (preferred_room_occupancy <= 3))) NOT VALID;
ALTER TABLE "public"."hhm_applications" VALIDATE CONSTRAINT "hhm_applications_room_occupancy";

-- add constraint: hhm_applications_roommate_preference on public.hhm_applications
ALTER TABLE "public"."hhm_applications" ADD CONSTRAINT "hhm_applications_roommate_preference" CHECK ((((roommate_preference)::text = 'private_room'::text) OR ((roommate_preference)::text = 'open_to_roommates'::text) OR ((roommate_preference)::text = 'prefer_roommates'::text) OR ((roommate_preference)::text = 'flexible'::text))) NOT VALID;
ALTER TABLE "public"."hhm_applications" VALIDATE CONSTRAINT "hhm_applications_roommate_preference";

COMMIT;

-- changes: 14 total, 0 destructive (0 gated), 0 manual-review
