//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "hhm_submission_outbox")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    #[sea_orm(unique_key = "hhm_submission_outbox_identity")]
    pub submission_kind: String,
    #[sea_orm(unique_key = "hhm_submission_outbox_identity")]
    pub submission_id: Uuid,
    pub payload_sha256: String,
    pub mirror_status: String,
    pub attempts: i32,
    pub next_attempt_at: DateTimeWithTimeZone,
    pub last_error_code: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
