//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "hhm_pre_interests")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub idempotency_key: String,
    pub payload_sha256: String,
    pub applicant_subject: Option<String>,
    pub email: String,
    pub linkedin_url: String,
    pub entrepreneurship_idea: String,
    pub stay_preference: String,
    pub privacy_notice_version: String,
    pub source_host: String,
    pub mirror_status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hhm_applications::Entity")]
    HhmApplications,
}

impl Related<super::hhm_applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HhmApplications.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
