//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "hhm_intake_uploads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub idempotency_key: String,
    pub payload_sha256: String,
    pub applicant_subject: Option<String>,
    pub kind: String,
    #[sea_orm(unique)]
    pub object_key: String,
    pub content_sha256: String,
    pub content_type: String,
    pub size_bytes: i64,
    pub status: String,
    pub expires_at: DateTimeWithTimeZone,
    pub uploaded_at: Option<DateTimeWithTimeZone>,
    pub verified_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
