//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "hhm_applications")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub idempotency_key: String,
    pub payload_sha256: String,
    pub pre_interest_id: Option<Uuid>,
    pub applicant_subject: Option<String>,
    pub email: String,
    pub linkedin_url: String,
    pub legal_name: String,
    pub date_of_birth: Date,
    pub nationality: String,
    pub phone: String,
    pub current_city: String,
    pub github_url: Option<String>,
    pub portfolio_url: Option<String>,
    pub entrepreneurship_idea: String,
    pub project_stage: String,
    pub stay_preference: String,
    pub preferred_start_month: Date,
    pub community_contribution: String,
    pub accessibility_or_accommodation_notes: Option<String>,
    pub resume_upload_id: Uuid,
    pub photo_id_upload_id: Uuid,
    pub age_and_identity_attestation: bool,
    pub privacy_notice_version: String,
    pub status: String,
    pub status_version: i64,
    pub last_admin_operation_id: Option<Uuid>,
    pub mirror_status: String,
    pub submitted_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub allergy_notes: Option<String>,
    pub noise_sensitivity: String,
    pub light_sensitivity: String,
    pub room_preference_notes: Option<String>,
    pub roommate_preference: String,
    pub preferred_room_occupancy: i16,
    pub roommate_for_lower_cost: bool,
    pub roommate_for_social_connection: bool,
    pub accommodation_data_consent: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hhm_intake_uploads::Entity",
        from = "Column::PhotoIdUploadId",
        to = "super::hhm_intake_uploads::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    HhmIntakeUploads2,
    #[sea_orm(
        belongs_to = "super::hhm_intake_uploads::Entity",
        from = "Column::ResumeUploadId",
        to = "super::hhm_intake_uploads::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    HhmIntakeUploads1,
    #[sea_orm(
        belongs_to = "super::hhm_pre_interests::Entity",
        from = "Column::PreInterestId",
        to = "super::hhm_pre_interests::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    HhmPreInterests,
}

impl Related<super::hhm_pre_interests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HhmPreInterests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
