//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "hhm_referrals")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub idempotency_key: String,
    pub payload_sha256: String,
    pub referrer_subject: String,
    pub referee_name: String,
    pub referee_email: String,
    pub referee_linkedin_url: String,
    pub relationship: String,
    pub rationale: String,
    pub stay_preference: Option<String>,
    pub nominee_consent_confirmed: bool,
    pub status: String,
    pub mirror_status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
