// @generated automatically by Diesel CLI.

pub mod public {
    diesel::table! {
        /// Representation of the `hhm_applications` table.
        ///
        /// (Automatically generated by Diesel.)
        hhm_applications (id) {
            /// The `id` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `idempotency_key` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            idempotency_key -> Varchar,
            /// The `payload_sha256` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Bpchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            payload_sha256 -> Bpchar,
            /// The `pre_interest_id` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Nullable<Uuid>`.
            ///
            /// (Automatically generated by Diesel.)
            pre_interest_id -> Nullable<Uuid>,
            /// The `applicant_subject` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Nullable<Varchar>`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            applicant_subject -> Nullable<Varchar>,
            /// The `email` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 320]
            email -> Varchar,
            /// The `linkedin_url` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 500]
            linkedin_url -> Varchar,
            /// The `legal_name` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 200]
            legal_name -> Varchar,
            /// The `date_of_birth` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Date`.
            ///
            /// (Automatically generated by Diesel.)
            date_of_birth -> Date,
            /// The `nationality` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 120]
            nationality -> Varchar,
            /// The `phone` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            phone -> Varchar,
            /// The `current_city` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 160]
            current_city -> Varchar,
            /// The `github_url` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Nullable<Varchar>`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 500]
            github_url -> Nullable<Varchar>,
            /// The `portfolio_url` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Nullable<Varchar>`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 500]
            portfolio_url -> Nullable<Varchar>,
            /// The `entrepreneurship_idea` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 8000]
            entrepreneurship_idea -> Varchar,
            /// The `project_stage` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            project_stage -> Varchar,
            /// The `stay_preference` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            stay_preference -> Varchar,
            /// The `preferred_start_month` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Date`.
            ///
            /// (Automatically generated by Diesel.)
            preferred_start_month -> Date,
            /// The `community_contribution` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 4000]
            community_contribution -> Varchar,
            /// The `accessibility_or_accommodation_notes` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Nullable<Varchar>`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 4000]
            accessibility_or_accommodation_notes -> Nullable<Varchar>,
            /// The `resume_upload_id` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            resume_upload_id -> Uuid,
            /// The `photo_id_upload_id` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            photo_id_upload_id -> Uuid,
            /// The `age_and_identity_attestation` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Bool`.
            ///
            /// (Automatically generated by Diesel.)
            age_and_identity_attestation -> Bool,
            /// The `privacy_notice_version` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            privacy_notice_version -> Varchar,
            /// The `status` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            status -> Varchar,
            /// The `status_version` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            status_version -> Int8,
            /// The `last_admin_operation_id` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Nullable<Uuid>`.
            ///
            /// (Automatically generated by Diesel.)
            last_admin_operation_id -> Nullable<Uuid>,
            /// The `mirror_status` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            mirror_status -> Varchar,
            /// The `submitted_at` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            submitted_at -> Timestamptz,
            /// The `updated_at` column of the `hhm_applications` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamptz,
        }
    }

    diesel::table! {
        /// Representation of the `hhm_intake_uploads` table.
        ///
        /// (Automatically generated by Diesel.)
        hhm_intake_uploads (id) {
            /// The `id` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `idempotency_key` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            idempotency_key -> Varchar,
            /// The `payload_sha256` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Bpchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            payload_sha256 -> Bpchar,
            /// The `applicant_subject` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Nullable<Varchar>`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            applicant_subject -> Nullable<Varchar>,
            /// The `kind` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            kind -> Varchar,
            /// The `object_key` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 1024]
            object_key -> Varchar,
            /// The `content_sha256` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Bpchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            content_sha256 -> Bpchar,
            /// The `content_type` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            content_type -> Varchar,
            /// The `size_bytes` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            size_bytes -> Int8,
            /// The `status` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            status -> Varchar,
            /// The `expires_at` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            expires_at -> Timestamptz,
            /// The `uploaded_at` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            uploaded_at -> Nullable<Timestamptz>,
            /// The `verified_at` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            verified_at -> Nullable<Timestamptz>,
            /// The `deleted_at` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            deleted_at -> Nullable<Timestamptz>,
            /// The `created_at` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamptz,
            /// The `updated_at` column of the `hhm_intake_uploads` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamptz,
        }
    }

    diesel::table! {
        /// Representation of the `hhm_pre_interests` table.
        ///
        /// (Automatically generated by Diesel.)
        hhm_pre_interests (id) {
            /// The `id` column of the `hhm_pre_interests` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `idempotency_key` column of the `hhm_pre_interests` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            idempotency_key -> Varchar,
            /// The `payload_sha256` column of the `hhm_pre_interests` table.
            ///
            /// Its SQL type is `Bpchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            payload_sha256 -> Bpchar,
            /// The `applicant_subject` column of the `hhm_pre_interests` table.
            ///
            /// Its SQL type is `Nullable<Varchar>`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            applicant_subject -> Nullable<Varchar>,
            /// The `email` column of the `hhm_pre_interests` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 320]
            email -> Varchar,
            /// The `linkedin_url` column of the `hhm_pre_interests` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 500]
            linkedin_url -> Varchar,
            /// The `entrepreneurship_idea` column of the `hhm_pre_interests` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 4000]
            entrepreneurship_idea -> Varchar,
            /// The `stay_preference` column of the `hhm_pre_interests` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            stay_preference -> Varchar,
            /// The `privacy_notice_version` column of the `hhm_pre_interests` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            privacy_notice_version -> Varchar,
            /// The `source_host` column of the `hhm_pre_interests` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            source_host -> Varchar,
            /// The `mirror_status` column of the `hhm_pre_interests` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            mirror_status -> Varchar,
            /// The `created_at` column of the `hhm_pre_interests` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamptz,
            /// The `updated_at` column of the `hhm_pre_interests` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamptz,
        }
    }

    diesel::table! {
        /// Representation of the `hhm_referrals` table.
        ///
        /// (Automatically generated by Diesel.)
        hhm_referrals (id) {
            /// The `id` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `idempotency_key` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            idempotency_key -> Varchar,
            /// The `payload_sha256` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Bpchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            payload_sha256 -> Bpchar,
            /// The `referrer_subject` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            referrer_subject -> Varchar,
            /// The `referee_name` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 200]
            referee_name -> Varchar,
            /// The `referee_email` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 320]
            referee_email -> Varchar,
            /// The `referee_linkedin_url` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 500]
            referee_linkedin_url -> Varchar,
            /// The `relationship` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 120]
            relationship -> Varchar,
            /// The `rationale` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 4000]
            rationale -> Varchar,
            /// The `stay_preference` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Nullable<Varchar>`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            stay_preference -> Nullable<Varchar>,
            /// The `nominee_consent_confirmed` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Bool`.
            ///
            /// (Automatically generated by Diesel.)
            nominee_consent_confirmed -> Bool,
            /// The `status` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            status -> Varchar,
            /// The `mirror_status` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            mirror_status -> Varchar,
            /// The `created_at` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamptz,
            /// The `updated_at` column of the `hhm_referrals` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamptz,
        }
    }

    diesel::table! {
        /// Representation of the `hhm_submission_outbox` table.
        ///
        /// (Automatically generated by Diesel.)
        hhm_submission_outbox (id) {
            /// The `id` column of the `hhm_submission_outbox` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `submission_kind` column of the `hhm_submission_outbox` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            submission_kind -> Varchar,
            /// The `submission_id` column of the `hhm_submission_outbox` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            submission_id -> Uuid,
            /// The `payload_sha256` column of the `hhm_submission_outbox` table.
            ///
            /// Its SQL type is `Bpchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            payload_sha256 -> Bpchar,
            /// The `mirror_status` column of the `hhm_submission_outbox` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 32]
            mirror_status -> Varchar,
            /// The `attempts` column of the `hhm_submission_outbox` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            attempts -> Int4,
            /// The `next_attempt_at` column of the `hhm_submission_outbox` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            next_attempt_at -> Timestamptz,
            /// The `last_error_code` column of the `hhm_submission_outbox` table.
            ///
            /// Its SQL type is `Nullable<Varchar>`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            last_error_code -> Nullable<Varchar>,
            /// The `created_at` column of the `hhm_submission_outbox` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamptz,
            /// The `updated_at` column of the `hhm_submission_outbox` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamptz,
        }
    }

    diesel::table! {
        /// Representation of the `hhm_user_points_accounts` table.
        ///
        /// (Automatically generated by Diesel.)
        hhm_user_points_accounts (subject) {
            /// The `subject` column of the `hhm_user_points_accounts` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            subject -> Varchar,
            /// The `id` column of the `hhm_user_points_accounts` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `balance` column of the `hhm_user_points_accounts` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            balance -> Int8,
            /// The `lifetime_earned` column of the `hhm_user_points_accounts` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            lifetime_earned -> Int8,
            /// The `lifetime_redeemed` column of the `hhm_user_points_accounts` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            lifetime_redeemed -> Int8,
            /// The `version` column of the `hhm_user_points_accounts` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            version -> Int8,
            /// The `updated_at` column of the `hhm_user_points_accounts` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamptz,
        }
    }

    diesel::table! {
        /// Representation of the `hhm_user_points_ledger` table.
        ///
        /// (Automatically generated by Diesel.)
        hhm_user_points_ledger (id) {
            /// The `id` column of the `hhm_user_points_ledger` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `idempotency_key` column of the `hhm_user_points_ledger` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            idempotency_key -> Varchar,
            /// The `subject` column of the `hhm_user_points_ledger` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            subject -> Varchar,
            /// The `delta` column of the `hhm_user_points_ledger` table.
            ///
            /// Its SQL type is `Int8`.
            ///
            /// (Automatically generated by Diesel.)
            delta -> Int8,
            /// The `reason_code` column of the `hhm_user_points_ledger` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            reason_code -> Varchar,
            /// The `source_submission_id` column of the `hhm_user_points_ledger` table.
            ///
            /// Its SQL type is `Nullable<Uuid>`.
            ///
            /// (Automatically generated by Diesel.)
            source_submission_id -> Nullable<Uuid>,
            /// The `actor_subject` column of the `hhm_user_points_ledger` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            actor_subject -> Varchar,
            /// The `created_at` column of the `hhm_user_points_ledger` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamptz,
        }
    }

    diesel::joinable!(hhm_applications -> hhm_pre_interests (pre_interest_id));

    diesel::allow_tables_to_appear_in_same_query!(hhm_applications, hhm_pre_interests,);
}
