#!/usr/bin/env python3
"""Verify immutable hhm-interfaces platform artifacts without network access."""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import subprocess
import sys


EXPECTED_REPOSITORY = "https://github.com/hacker-house-medellin/hhm-interfaces"
EXPECTED_REVISION = "b66988b856946ff028085323ff502796b97e0012"
EXPECTED_ARTIFACTS = {
    "generated/platform/sql/schema.sql": (
        "vendor/hhm-interfaces/platform/sql/schema.sql",
        "c2c9a902949cb37246e15db32f4faa42c325dc46675c53a39161dd9ce8751c99",
        24393,
    ),
    "generated/platform/rust/types.rs": (
        "vendor/hhm-interfaces/platform/rust/types.rs",
        "3c0c6da2a6dfa372eae5b54134812d4b3ba8823de187859647ae619ed75dbca4",
        19029,
    ),
    "generated/platform/seaorm/entities.rs": (
        "vendor/hhm-interfaces/platform/seaorm/entities.rs",
        "4839606b98e649abf1ca711b27d017124353a17eb3bc304f7c96114ac8c35899",
        43229,
    ),
    "generated/platform/diesel/schema.rs": (
        "vendor/hhm-interfaces/platform/diesel/schema.rs",
        "8213cd9fc0e908aa2cfb91973b73e6ad9b8d6aa6a422d99ccbf2fe07ae5eda63",
        45503,
    ),
}


def fail(message: str) -> None:
    raise SystemExit(f"platform vendor verification failed: {message}")


def sha256(contents: bytes) -> str:
    return hashlib.sha256(contents).hexdigest()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=pathlib.Path,
        help="optional checkout of hhm-interfaces at the pinned revision",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    repository = pathlib.Path(__file__).resolve().parent.parent
    manifest_path = repository / "vendor/hhm-interfaces/platform/SOURCE.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    if manifest.get("schema_version") != 1:
        fail("unsupported SOURCE.json schema version")
    if manifest.get("repository") != EXPECTED_REPOSITORY:
        fail("upstream repository changed")
    revision = manifest.get("revision")
    if revision != EXPECTED_REVISION or re.fullmatch(r"[0-9a-f]{40}", revision or "") is None:
        fail("upstream revision is not the reviewed full production SHA")
    if manifest.get("release_state") != "production":
        fail("upstream revision is not marked production")

    observed = {
        entry["upstream_path"]: (
            entry["vendored_path"],
            entry["sha256"],
            entry["bytes"],
        )
        for entry in manifest.get("artifacts", [])
    }
    if observed != EXPECTED_ARTIFACTS:
        fail("artifact manifest differs from the reviewed allowlist")

    vendored: dict[str, bytes] = {}
    for upstream_path, (vendored_path, expected_hash, expected_bytes) in observed.items():
        contents = (repository / vendored_path).read_bytes()
        vendored[upstream_path] = contents
        if len(contents) != expected_bytes:
            fail(f"unexpected byte length for {vendored_path}")
        if sha256(contents) != expected_hash:
            fail(f"SHA-256 mismatch for {vendored_path}")
        first_line = contents.splitlines()[0]
        if b"GENERATED by ores-contracts" not in first_line:
            fail(f"generated provenance header missing from {vendored_path}")

    migration = repository / manifest["migration_copy"]
    if migration.read_bytes() != vendored["generated/platform/sql/schema.sql"]:
        fail("generated platform migration is not byte-identical to vendored SQL")

    cargo_manifest = (repository / "crates/persistence/Cargo.toml").read_text(encoding="utf-8")
    if EXPECTED_REVISION not in cargo_manifest:
        fail("persistence Cargo dependency is not pinned to the platform revision")
    cargo_lock = (repository / "Cargo.lock").read_text(encoding="utf-8")
    if f"rev={EXPECTED_REVISION}#{EXPECTED_REVISION}" not in cargo_lock:
        fail("Cargo.lock does not resolve hhm-interfaces to the exact platform revision")

    if args.source is not None:
        source = args.source.resolve()
        head = subprocess.run(
            ["git", "-C", str(source), "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
        if head != EXPECTED_REVISION:
            fail(f"interface checkout is at {head}, not {EXPECTED_REVISION}")
        for upstream_path, contents in vendored.items():
            if (source / upstream_path).read_bytes() != contents:
                fail(f"vendored bytes differ from {upstream_path} at {EXPECTED_REVISION}")

    print(
        f"platform vendor verified: {len(vendored)} artifacts at {EXPECTED_REVISION}",
        file=sys.stdout,
    )


if __name__ == "__main__":
    main()
